AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: A serverless component for CSV to XLSX conversion
Parameters:
  ConversionTimeout:
    Type: Number
    Default: 60
  InputBucketName:
    Type: String
    Default: 's3-lambda-csv-input-s3-bucket'
  OutputBucketName:
    Type: String
    Default: 's3-lambda-xlsx-output-s3-bucket'
Resources:
  InputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref InputBucketName
  ConvertFileFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Timeout: !Ref ConversionTimeout
      MemorySize: 512
      Runtime: nodejs18.x
      Policies:
      - S3ReadPolicy:
          BucketName: !Ref InputBucketName
      - S3CrudPolicy:
          BucketName: !Ref OutputBucketName
      Environment:
        Variables:
          RESULTS_BUCKET_NAME: !Ref OutputS3Bucket
          EXTENSION: '.xlsx'
          MIME_TYPE: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
      Events:
        FileUpload:
          Type: S3
          Properties:
            Bucket: !Ref InputS3Bucket
            Events: s3:ObjectCreated:*
  OutputS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketName

Outputs:
  InputS3Bucket:
    Description: Input S3 bucket
    Value: !Ref InputS3Bucket
  OutputS3Bucket:
    Description: Output S3 bucket
    Value: !Ref OutputS3Bucket

